# Generated by Django 4.2.3 on 2023-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WazaAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
