# Generated by Django 4.2.3 on 2023-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WazaAdmin", "0002_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_email", models.EmailField(max_length=254, null=True)),
                ("content", models.TextField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField()),
            ],
        ),
    ]
